# Added due to required but conditional checks
# Read more: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

name: 'binge checks'
on:
  pull_request:
    paths-ignore:
      - "/binge"
jobs:
  sh-checker:
    name: Shellcheck + Shfmt
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required: did not modify binge"'
  check-exec:
    name: Executable Bit
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required: did not modify binge"'
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required: did not modify binge"'
